### ISSUE TITLE
Does this tool support for Mac M1?

### ISSUE THREAD

**Issue by lexuanquynh** [graphcool/get-graphql-schema#75]
I'm try using:
```py
npm install -g get-graphql-schema
```
and succefully. But I can't use this tool in my Mac M1.

```
 command not found: get-graphql-schema
```
Does this tool support for Mac M1?
Thanks.

**Comment by turboflo** [comment]
Try `nvm install v15` before installing get-graphql-schema,  it worked for me.

**Comment by madabhaviamit** [comment]
I am facing same issue, Tried with **nvm install v15**, It did not resolve @turboflo 

@lexuanquynh, were you able to solve this issue?

**Comment by Hyferion** [comment]
Same issue on my m2

**Comment by lexuanquynh** [comment]
@madabhaviamit 
this is my solution:
## Download the schema.

1. Install get-graphql-schema with the command:
```
npm install -g get-graphql-schema
```

If you are using Macbook silicon, make sure apollo-cli is not installed. If it exists, remove it with the command:
```
brew uninstall apollo-cli
```

2. Download the schema from the backend Apollo website.



The schema must be download with the command:

```
get-graphql-schema https:/<your_backend>/api/v1/graphql --json > schema.json
```
After executing this command, you will see the schema.json file.
This file is used to generate graphQL queries in the iOS project.

## Writing the graphQL query.

<by your backend API script.>

For more information on how to write GraphQL scripts, please visit this [website](https://graphql.org/graphql-js/).

You need to include the file in your iOS project.

You have to create the Apollo build phase like as this image:

![image](https://github.com/prisma-labs/get-graphql-schema/assets/17588791/91b3a9c3-10d1-43a8-83da-ab681cb49d62)

The reason it is commented out is because the API file was created from this build phase.
You will need to uncomment this line the first time you build.

The API file will automatically generate and you don't need change this file.

For more information, please [click here.](https://www.apollographql.com/docs/ios/v0-legacy/installation)

All done. Enjoy coding.

**Comment by lexuanquynh** [comment]
@madabhaviamit @Hyferion 
Sorry I missed the notification from Github.

**Comment by trupeshv** [comment]
@lexuanquynh 
you can use npx as prefix and then try once.
Like.. 
npx get-graphql-schema -H "x-hasura-admin-secret:[ADMIN-SECRET-KEY]"  [END-POINT] --introspect > lib/schema.graphql
